flowchart LR
  classDef expectedOnly stroke-dasharray: 5 5,stroke:#666,fill:#fff8dc;
  classDef observedOnly stroke:#1e88e5,fill:#e3f2fd;
  N_audio_input_node["/audio_input_node&lt;br/&gt;[asr_runtime_nodes]"]
  class N_audio_input_node expectedOnly;
  S_asr_runtime_audio_reconfigure{{"/asr/runtime/audio/reconfigure"}}
  class S_asr_runtime_audio_reconfigure expectedOnly;
  N_audio_input_node -.->|server: /asr/runtime/audio/reconfigure&lt;br/&gt;ReconfigureRuntime| S_asr_runtime_audio_reconfigure
  S_asr_runtime_audio_start_session{{"/asr/runtime/audio/start_session"}}
  class S_asr_runtime_audio_start_session expectedOnly;
  N_audio_input_node -.->|server: /asr/runtime/audio/start_session&lt;br/&gt;StartRuntimeSession| S_asr_runtime_audio_start_session
  S_asr_runtime_audio_stop_session{{"/asr/runtime/audio/stop_session"}}
  class S_asr_runtime_audio_stop_session expectedOnly;
  N_audio_input_node -.->|server: /asr/runtime/audio/stop_session&lt;br/&gt;StopRuntimeSession| S_asr_runtime_audio_stop_session
  N_asr_orchestrator_node["/asr_orchestrator_node&lt;br/&gt;[asr_runtime_nodes]"]
  class N_asr_orchestrator_node expectedOnly;
  S_asr_runtime_get_status{{"/asr/runtime/get_status"}}
  class S_asr_runtime_get_status expectedOnly;
  N_asr_orchestrator_node -.->|server: /asr/runtime/get_status&lt;br/&gt;GetAsrStatus| S_asr_runtime_get_status
  S_asr_runtime_list_backends{{"/asr/runtime/list_backends"}}
  class S_asr_runtime_list_backends expectedOnly;
  N_asr_orchestrator_node -.->|server: /asr/runtime/list_backends&lt;br/&gt;ListBackends| S_asr_runtime_list_backends
  N_audio_preprocess_node["/audio_preprocess_node&lt;br/&gt;[asr_runtime_nodes]"]
  class N_audio_preprocess_node expectedOnly;
  S_asr_runtime_preprocess_reconfigure{{"/asr/runtime/preprocess/reconfigure"}}
  class S_asr_runtime_preprocess_reconfigure expectedOnly;
  N_audio_preprocess_node -.->|server: /asr/runtime/preprocess/reconfigure&lt;br/&gt;ReconfigureRuntime| S_asr_runtime_preprocess_reconfigure
  S_asr_runtime_recognize_once{{"/asr/runtime/recognize_once"}}
  class S_asr_runtime_recognize_once expectedOnly;
  N_asr_orchestrator_node -.->|server: /asr/runtime/recognize_once&lt;br/&gt;RecognizeOnce| S_asr_runtime_recognize_once
  S_asr_runtime_reconfigure{{"/asr/runtime/reconfigure"}}
  class S_asr_runtime_reconfigure expectedOnly;
  N_asr_orchestrator_node -.->|server: /asr/runtime/reconfigure&lt;br/&gt;ReconfigureRuntime| S_asr_runtime_reconfigure
  S_asr_runtime_start_session{{"/asr/runtime/start_session"}}
  class S_asr_runtime_start_session expectedOnly;
  N_asr_orchestrator_node -.->|server: /asr/runtime/start_session&lt;br/&gt;StartRuntimeSession| S_asr_runtime_start_session
  S_asr_runtime_stop_session{{"/asr/runtime/stop_session"}}
  class S_asr_runtime_stop_session expectedOnly;
  N_asr_orchestrator_node -.->|server: /asr/runtime/stop_session&lt;br/&gt;StopRuntimeSession| S_asr_runtime_stop_session
  N_vad_segmenter_node["/vad_segmenter_node&lt;br/&gt;[asr_runtime_nodes]"]
  class N_vad_segmenter_node expectedOnly;
  S_asr_runtime_vad_reconfigure{{"/asr/runtime/vad/reconfigure"}}
  class S_asr_runtime_vad_reconfigure expectedOnly;
  N_vad_segmenter_node -.->|server: /asr/runtime/vad/reconfigure&lt;br/&gt;ReconfigureRuntime| S_asr_runtime_vad_reconfigure
  N_benchmark_manager_node["/benchmark_manager_node&lt;br/&gt;[asr_benchmark_nodes]"]
  class N_benchmark_manager_node expectedOnly;
  S_benchmark_get_status{{"/benchmark/get_status"}}
  class S_benchmark_get_status expectedOnly;
  N_benchmark_manager_node -.->|server: /benchmark/get_status&lt;br/&gt;GetBenchmarkStatus| S_benchmark_get_status
  S_config_list_profiles{{"/config/list_profiles"}}
  class S_config_list_profiles expectedOnly;
  N_asr_orchestrator_node -.->|server: /config/list_profiles&lt;br/&gt;ListProfiles| S_config_list_profiles
  S_config_validate{{"/config/validate"}}
  class S_config_validate expectedOnly;
  N_asr_orchestrator_node -.->|server: /config/validate&lt;br/&gt;ValidateConfig| S_config_validate
  S_datasets_list{{"/datasets/list"}}
  class S_datasets_list expectedOnly;
  N_benchmark_manager_node -.->|server: /datasets/list&lt;br/&gt;ListDatasets| S_datasets_list
  S_datasets_register{{"/datasets/register"}}
  class S_datasets_register expectedOnly;
  N_benchmark_manager_node -.->|server: /datasets/register&lt;br/&gt;RegisterDataset| S_datasets_register
  N_GatewayRosClient["/GatewayRosClient&lt;br/&gt;[asr_gateway]"]
  class N_GatewayRosClient expectedOnly;
  S_unknown__service__client{{"unknown::service::client"}}
  class S_unknown__service__client expectedOnly;
  S_unknown__service__client -.->|client: unknown::service::client&lt;br/&gt;service_type| N_GatewayRosClient
  S_unknown__service__client -.->|client: unknown::service::client&lt;br/&gt;service_type| N_asr_orchestrator_node
  T_unknown__topic__pub(["unknown::topic::pub"])
  class T_unknown__topic__pub expectedOnly;
  N_asr_orchestrator_node -.->|pub: unknown::topic::pub&lt;br/&gt;AsrResult| T_unknown__topic__pub
  N_audio_input_node -.->|pub: unknown::topic::pub&lt;br/&gt;AudioChunk| T_unknown__topic__pub
  N_audio_preprocess_node -.->|pub: unknown::topic::pub&lt;br/&gt;AudioChunk| T_unknown__topic__pub
  N_vad_segmenter_node -.->|pub: unknown::topic::pub&lt;br/&gt;SpeechActivity| T_unknown__topic__pub
  N_RuntimeObserver["/RuntimeObserver&lt;br/&gt;[asr_gateway]"]
  class N_RuntimeObserver expectedOnly;
  T_unknown__topic__sub(["unknown::topic::sub"])
  class T_unknown__topic__sub expectedOnly;
  T_unknown__topic__sub -.->|sub: unknown::topic::sub&lt;br/&gt;AsrResult| N_RuntimeObserver
  T_unknown__topic__sub -.->|sub: unknown::topic::sub&lt;br/&gt;AudioSegment| N_asr_orchestrator_node
  T_unknown__topic__sub -.->|sub: unknown::topic::sub&lt;br/&gt;AudioChunk| N_audio_preprocess_node
  T_unknown__topic__sub -.->|sub: unknown::topic::sub&lt;br/&gt;AudioChunk| N_vad_segmenter_node
