profile_id: providers/aws_cloud
inherits: []
provider_id: aws
adapter: asr_provider_aws.aws_provider.AwsProvider
settings:
  region: eu-north-1
  s3_bucket: ros2ws-asr-787345513049-eu-north-1
  media_format: wav
  cleanup: true
credentials_ref: secrets/refs/aws_profile.yaml
